// https://wiki.nesdev.org/w/index.php?title=CPU_addressing_modes
pub const AddressingMode = enum {
    implicit,
    accumulator,
    immediate,
    zeroPage,
    zeroPageX,
    zeroPageY,
    absolute,
    absoluteX,
    absoluteXWithPenalty,
    absoluteY,
    absoluteYWithPenalty,
    relative,
    indirect,
    indexedIndirect,
    indirectIndexed,
    indirectIndexedWithPenalty,
};

// https://www.nesdev.org/wiki/6502_instructions
pub const Mnemonic = enum {
    // Load/Store Operations
    LDA,
    LDX,
    LDY,
    STA,
    STX,
    STY,
    // Register Operations
    TAX,
    TSX,
    TAY,
    TXA,
    TXS,
    TYA,
    // Stack instructions
    PHA,
    PHP,
    PLA,
    PLP,
    // Logical instructions
    AND,
    EOR,
    ORA,
    BIT,
    // Arithmetic instructions
    ADC,
    SBC,
    CMP,
    CPX,
    CPY,
    // Increment/Decrement instructions
    INC,
    INX,
    INY,
    DEC,
    DEX,
    DEY,
    // Shift instructions
    ASL,
    LSR,
    ROL,
    ROR,
    // Jump instructions
    JMP,
    JSR,
    RTS,
    RTI,
    // Branch instructions
    BCC,
    BCS,
    BEQ,
    BMI,
    BNE,
    BPL,
    BVC,
    BVS,
    // Flag control instructions
    CLC,
    CLD,
    CLI,
    CLV,
    SEC,
    SED,
    SEI,
    // Misc
    BRK,
    NOP,
    // Unofficial
    LAX,
    SAX,
    DCP,
    ISB,
    SLO,
    RLA,
    SRE,
    RRA,
};

pub const Instruction = struct {
    mnemonic: Mnemonic,
    addressingMode: AddressingMode,
};

pub fn decode(opcode: u8) Instruction {
    return switch (opcode) {
        0x69 => .{ Mnemonic.ADC, AddressingMode.immediate },
        0x65 => .{ Mnemonic.ADC, AddressingMode.zeroPage },
        0x75 => .{ Mnemonic.ADC, AddressingMode.zeroPageX },
        0x6D => .{ Mnemonic.ADC, AddressingMode.absolute },
        0x7D => .{ Mnemonic.ADC, AddressingMode.absoluteXWithPenalty },
        0x79 => .{ Mnemonic.ADC, AddressingMode.absoluteYWithPenalty },
        0x61 => .{ Mnemonic.ADC, AddressingMode.indexedIndirect },
        0x71 => .{ Mnemonic.ADC, AddressingMode.indirectIndexedWithPenalty },

        0x29 => .{ Mnemonic.AND, AddressingMode.immediate },
        0x25 => .{ Mnemonic.AND, AddressingMode.zeroPage },
        0x35 => .{ Mnemonic.AND, AddressingMode.zeroPageX },
        0x2D => .{ Mnemonic.AND, AddressingMode.absolute },
        0x3D => .{ Mnemonic.AND, AddressingMode.absoluteXWithPenalty },
        0x39 => .{ Mnemonic.AND, AddressingMode.absoluteYWithPenalty },
        0x21 => .{ Mnemonic.AND, AddressingMode.indexedIndirect },
        0x31 => .{ Mnemonic.AND, AddressingMode.indirectIndexedWithPenalty },

        0x0A => .{ Mnemonic.ASL, AddressingMode.accumulator },
        0x06 => .{ Mnemonic.ASL, AddressingMode.zeroPage },
        0x16 => .{ Mnemonic.ASL, AddressingMode.zeroPageX },
        0x0E => .{ Mnemonic.ASL, AddressingMode.absolute },
        0x1E => .{ Mnemonic.ASL, AddressingMode.absoluteX },

        0x90 => .{ Mnemonic.BCC, AddressingMode.relative },
        0xB0 => .{ Mnemonic.BCS, AddressingMode.relative },
        0xF0 => .{ Mnemonic.BEQ, AddressingMode.relative },

        0x24 => .{ Mnemonic.BIT, AddressingMode.zeroPage },
        0x2C => .{ Mnemonic.BIT, AddressingMode.absolute },

        0x30 => .{ Mnemonic.BMI, AddressingMode.relative },
        0xD0 => .{ Mnemonic.BNE, AddressingMode.relative },
        0x10 => .{ Mnemonic.BPL, AddressingMode.relative },

        0x00 => .{ Mnemonic.BRK, AddressingMode.implicit },

        0x50 => .{ Mnemonic.BVC, AddressingMode.relative },
        0x70 => .{ Mnemonic.BVS, AddressingMode.relative },

        0x18 => .{ Mnemonic.CLC, AddressingMode.implicit },
        0xD8 => .{ Mnemonic.CLD, AddressingMode.implicit },
        0x58 => .{ Mnemonic.CLI, AddressingMode.implicit },
        0xB8 => .{ Mnemonic.CLV, AddressingMode.implicit },

        0xC9 => .{ Mnemonic.CMP, AddressingMode.immediate },
        0xC5 => .{ Mnemonic.CMP, AddressingMode.zeroPage },
        0xD5 => .{ Mnemonic.CMP, AddressingMode.zeroPageX },
        0xCD => .{ Mnemonic.CMP, AddressingMode.absolute },
        0xDD => .{ Mnemonic.CMP, AddressingMode.absoluteXWithPenalty },
        0xD9 => .{ Mnemonic.CMP, AddressingMode.absoluteYWithPenalty },
        0xC1 => .{ Mnemonic.CMP, AddressingMode.indexedIndirect },
        0xD1 => .{ Mnemonic.CMP, AddressingMode.indirectIndexedWithPenalty },

        0xE0 => .{ Mnemonic.CPX, AddressingMode.immediate },
        0xE4 => .{ Mnemonic.CPX, AddressingMode.zeroPage },
        0xEC => .{ Mnemonic.CPX, AddressingMode.absolute },
        0xC0 => .{ Mnemonic.CPY, AddressingMode.immediate },
        0xC4 => .{ Mnemonic.CPY, AddressingMode.zeroPage },
        0xCC => .{ Mnemonic.CPY, AddressingMode.absolute },

        0xC6 => .{ Mnemonic.DEC, AddressingMode.zeroPage },
        0xD6 => .{ Mnemonic.DEC, AddressingMode.zeroPageX },
        0xCE => .{ Mnemonic.DEC, AddressingMode.absolute },
        0xDE => .{ Mnemonic.DEC, AddressingMode.absoluteX },

        0xCA => .{ Mnemonic.DEX, AddressingMode.implicit },
        0x88 => .{ Mnemonic.DEY, AddressingMode.implicit },

        0x49 => .{ Mnemonic.EOR, AddressingMode.immediate },
        0x45 => .{ Mnemonic.EOR, AddressingMode.zeroPage },
        0x55 => .{ Mnemonic.EOR, AddressingMode.zeroPageX },
        0x4D => .{ Mnemonic.EOR, AddressingMode.absolute },
        0x5D => .{ Mnemonic.EOR, AddressingMode.absoluteXWithPenalty },
        0x59 => .{ Mnemonic.EOR, AddressingMode.absoluteYWithPenalty },
        0x41 => .{ Mnemonic.EOR, AddressingMode.indexedIndirect },
        0x51 => .{ Mnemonic.EOR, AddressingMode.indirectIndexedWithPenalty },

        0xE6 => .{ Mnemonic.INC, AddressingMode.zeroPage },
        0xF6 => .{ Mnemonic.INC, AddressingMode.zeroPageX },
        0xEE => .{ Mnemonic.INC, AddressingMode.absolute },
        0xFE => .{ Mnemonic.INC, AddressingMode.absoluteX },

        0xE8 => .{ Mnemonic.INX, AddressingMode.implicit },
        0xC8 => .{ Mnemonic.INY, AddressingMode.implicit },

        0x4C => .{ Mnemonic.JMP, AddressingMode.absolute },
        0x6C => .{ Mnemonic.JMP, AddressingMode.indirect },

        0x20 => .{ Mnemonic.JSR, AddressingMode.absolute },

        0xA9 => .{ Mnemonic.LDA, AddressingMode.immediate },
        0xA5 => .{ Mnemonic.LDA, AddressingMode.zeroPage },
        0xB5 => .{ Mnemonic.LDA, AddressingMode.zeroPageX },
        0xAD => .{ Mnemonic.LDA, AddressingMode.absolute },
        0xBD => .{ Mnemonic.LDA, AddressingMode.absoluteXWithPenalty },
        0xB9 => .{ Mnemonic.LDA, AddressingMode.absoluteYWithPenalty },
        0xA1 => .{ Mnemonic.LDA, AddressingMode.indexedIndirect },
        0xB1 => .{ Mnemonic.LDA, AddressingMode.indirectIndexedWithPenalty },

        0xA2 => .{ Mnemonic.LDX, AddressingMode.immediate },
        0xA6 => .{ Mnemonic.LDX, AddressingMode.zeroPage },
        0xB6 => .{ Mnemonic.LDX, AddressingMode.zeroPageY },
        0xAE => .{ Mnemonic.LDX, AddressingMode.absolute },
        0xBE => .{ Mnemonic.LDX, AddressingMode.absoluteYWithPenalty },

        0xA0 => .{ Mnemonic.LDY, AddressingMode.immediate },
        0xA4 => .{ Mnemonic.LDY, AddressingMode.zeroPage },
        0xB4 => .{ Mnemonic.LDY, AddressingMode.zeroPageX },
        0xAC => .{ Mnemonic.LDY, AddressingMode.absolute },
        0xBC => .{ Mnemonic.LDY, AddressingMode.absoluteXWithPenalty },

        0x4A => .{ Mnemonic.LSR, AddressingMode.accumulator },
        0x46 => .{ Mnemonic.LSR, AddressingMode.zeroPage },
        0x56 => .{ Mnemonic.LSR, AddressingMode.zeroPageX },
        0x4E => .{ Mnemonic.LSR, AddressingMode.absolute },
        0x5E => .{ Mnemonic.LSR, AddressingMode.absoluteX },

        0x09 => .{ Mnemonic.ORA, AddressingMode.immediate },
        0x05 => .{ Mnemonic.ORA, AddressingMode.zeroPage },
        0x15 => .{ Mnemonic.ORA, AddressingMode.zeroPageX },
        0x0D => .{ Mnemonic.ORA, AddressingMode.absolute },
        0x1D => .{ Mnemonic.ORA, AddressingMode.absoluteXWithPenalty },
        0x19 => .{ Mnemonic.ORA, AddressingMode.absoluteYWithPenalty },
        0x01 => .{ Mnemonic.ORA, AddressingMode.indexedIndirect },
        0x11 => .{ Mnemonic.ORA, AddressingMode.indirectIndexedWithPenalty },

        0x48 => .{ Mnemonic.PHA, AddressingMode.implicit },
        0x08 => .{ Mnemonic.PHP, AddressingMode.implicit },
        0x68 => .{ Mnemonic.PLA, AddressingMode.implicit },
        0x28 => .{ Mnemonic.PLP, AddressingMode.implicit },

        0x2A => .{ Mnemonic.ROL, AddressingMode.accumulator },
        0x26 => .{ Mnemonic.ROL, AddressingMode.zeroPage },
        0x36 => .{ Mnemonic.ROL, AddressingMode.zeroPageX },
        0x2E => .{ Mnemonic.ROL, AddressingMode.absolute },
        0x3E => .{ Mnemonic.ROL, AddressingMode.absoluteX },

        0x6A => .{ Mnemonic.ROR, AddressingMode.accumulator },
        0x66 => .{ Mnemonic.ROR, AddressingMode.zeroPage },
        0x76 => .{ Mnemonic.ROR, AddressingMode.zeroPageX },
        0x6E => .{ Mnemonic.ROR, AddressingMode.absolute },
        0x7E => .{ Mnemonic.ROR, AddressingMode.absoluteX },

        0x40 => .{ Mnemonic.RTI, AddressingMode.implicit },
        0x60 => .{ Mnemonic.RTS, AddressingMode.implicit },

        0xE9 => .{ Mnemonic.SBC, AddressingMode.immediate },
        0xE5 => .{ Mnemonic.SBC, AddressingMode.zeroPage },
        0xF5 => .{ Mnemonic.SBC, AddressingMode.zeroPageX },
        0xED => .{ Mnemonic.SBC, AddressingMode.absolute },
        0xFD => .{ Mnemonic.SBC, AddressingMode.absoluteXWithPenalty },
        0xF9 => .{ Mnemonic.SBC, AddressingMode.absoluteYWithPenalty },
        0xE1 => .{ Mnemonic.SBC, AddressingMode.indexedIndirect },
        0xF1 => .{ Mnemonic.SBC, AddressingMode.indirectIndexedWithPenalty },

        0x38 => .{ Mnemonic.SEC, AddressingMode.implicit },
        0xF8 => .{ Mnemonic.SED, AddressingMode.implicit },
        0x78 => .{ Mnemonic.SEI, AddressingMode.implicit },

        0x85 => .{ Mnemonic.STA, AddressingMode.zeroPage },
        0x95 => .{ Mnemonic.STA, AddressingMode.zeroPageX },
        0x8D => .{ Mnemonic.STA, AddressingMode.absolute },
        0x9D => .{ Mnemonic.STA, AddressingMode.absoluteX },
        0x99 => .{ Mnemonic.STA, AddressingMode.absoluteY },
        0x81 => .{ Mnemonic.STA, AddressingMode.indexedIndirect },
        0x91 => .{ Mnemonic.STA, AddressingMode.indirectIndexed },

        0x86 => .{ Mnemonic.STX, AddressingMode.zeroPage },
        0x96 => .{ Mnemonic.STX, AddressingMode.zeroPageY },
        0x8E => .{ Mnemonic.STX, AddressingMode.absolute },
        0x84 => .{ Mnemonic.STY, AddressingMode.zeroPage },
        0x94 => .{ Mnemonic.STY, AddressingMode.zeroPageX },
        0x8C => .{ Mnemonic.STY, AddressingMode.absolute },

        0xAA => .{ Mnemonic.TAX, AddressingMode.implicit },
        0xA8 => .{ Mnemonic.TAY, AddressingMode.implicit },
        0xBA => .{ Mnemonic.TSX, AddressingMode.implicit },
        0x8A => .{ Mnemonic.TXA, AddressingMode.implicit },
        0x9A => .{ Mnemonic.TXS, AddressingMode.implicit },
        0x98 => .{ Mnemonic.TYA, AddressingMode.implicit },

        0x04, 0x44, 0x64 => .{ Mnemonic.NOP, AddressingMode.zeroPage },
        0x0C => .{ Mnemonic.NOP, AddressingMode.absolute },
        0x14, 0x34, 0x54, 0x74, 0xD4, 0xF4 => .{ Mnemonic.NOP, AddressingMode.zeroPageX },
        0x1A, 0x3A, 0x5A, 0x7A, 0xDA, 0xEA, 0xFA => .{ Mnemonic.NOP, AddressingMode.implicit },
        0x1C, 0x3C, 0x5C, 0x7C, 0xDC, 0xFC => .{ Mnemonic.NOP, AddressingMode.absoluteXWithPenalty },
        0x80, 0x82, 0x89, 0xc2, 0xE2 => .{ Mnemonic.NOP, AddressingMode.immediate },

        // unofficial
        0xEB => .{ Mnemonic.SBC, AddressingMode.immediate },

        0xA3 => .{ Mnemonic.LAX, AddressingMode.indexedIndirect },
        0xA7 => .{ Mnemonic.LAX, AddressingMode.zeroPage },
        0xAB => .{ Mnemonic.LAX, AddressingMode.immediate },
        0xAF => .{ Mnemonic.LAX, AddressingMode.absolute },
        0xB3 => .{ Mnemonic.LAX, AddressingMode.indirectIndexedWithPenalty },
        0xB7 => .{ Mnemonic.LAX, AddressingMode.zeroPageY },
        0xBF => .{ Mnemonic.LAX, AddressingMode.absoluteYWithPenalty },

        0x83 => .{ Mnemonic.SAX, AddressingMode.indexedIndirect },
        0x87 => .{ Mnemonic.SAX, AddressingMode.zeroPage },
        0x8F => .{ Mnemonic.SAX, AddressingMode.absolute },
        0x97 => .{ Mnemonic.SAX, AddressingMode.zeroPageY },

        0xC3 => .{ Mnemonic.DCP, AddressingMode.indexedIndirect },
        0xC7 => .{ Mnemonic.DCP, AddressingMode.zeroPage },
        0xCF => .{ Mnemonic.DCP, AddressingMode.absolute },
        0xD3 => .{ Mnemonic.DCP, AddressingMode.indirectIndexed },
        0xD7 => .{ Mnemonic.DCP, AddressingMode.zeroPageX },
        0xDB => .{ Mnemonic.DCP, AddressingMode.absoluteY },
        0xDF => .{ Mnemonic.DCP, AddressingMode.absoluteX },

        0xE3 => .{ Mnemonic.ISB, AddressingMode.indexedIndirect },
        0xE7 => .{ Mnemonic.ISB, AddressingMode.zeroPage },
        0xEF => .{ Mnemonic.ISB, AddressingMode.absolute },
        0xF3 => .{ Mnemonic.ISB, AddressingMode.indirectIndexed },
        0xF7 => .{ Mnemonic.ISB, AddressingMode.zeroPageX },
        0xFB => .{ Mnemonic.ISB, AddressingMode.absoluteY },
        0xFF => .{ Mnemonic.ISB, AddressingMode.absoluteX },

        0x03 => .{ Mnemonic.SLO, AddressingMode.indexedIndirect },
        0x07 => .{ Mnemonic.SLO, AddressingMode.zeroPage },
        0x0F => .{ Mnemonic.SLO, AddressingMode.absolute },
        0x13 => .{ Mnemonic.SLO, AddressingMode.indirectIndexed },
        0x17 => .{ Mnemonic.SLO, AddressingMode.zeroPageX },
        0x1B => .{ Mnemonic.SLO, AddressingMode.absoluteY },
        0x1F => .{ Mnemonic.SLO, AddressingMode.absoluteX },

        0x23 => .{ Mnemonic.RLA, AddressingMode.indexedIndirect },
        0x27 => .{ Mnemonic.RLA, AddressingMode.zeroPage },
        0x2F => .{ Mnemonic.RLA, AddressingMode.absolute },
        0x33 => .{ Mnemonic.RLA, AddressingMode.indirectIndexed },
        0x37 => .{ Mnemonic.RLA, AddressingMode.zeroPageX },
        0x3B => .{ Mnemonic.RLA, AddressingMode.absoluteY },
        0x3F => .{ Mnemonic.RLA, AddressingMode.absoluteX },

        0x43 => .{ Mnemonic.SRE, AddressingMode.indexedIndirect },
        0x47 => .{ Mnemonic.SRE, AddressingMode.zeroPage },
        0x4F => .{ Mnemonic.SRE, AddressingMode.absolute },
        0x53 => .{ Mnemonic.SRE, AddressingMode.indirectIndexed },
        0x57 => .{ Mnemonic.SRE, AddressingMode.zeroPageX },
        0x5B => .{ Mnemonic.SRE, AddressingMode.absoluteY },
        0x5F => .{ Mnemonic.SRE, AddressingMode.absoluteX },

        0x63 => .{ Mnemonic.RRA, AddressingMode.indexedIndirect },
        0x67 => .{ Mnemonic.RRA, AddressingMode.zeroPage },
        0x6F => .{ Mnemonic.RRA, AddressingMode.absolute },
        0x73 => .{ Mnemonic.RRA, AddressingMode.indirectIndexed },
        0x77 => .{ Mnemonic.RRA, AddressingMode.zeroPageX },
        0x7B => .{ Mnemonic.RRA, AddressingMode.absoluteY },
        0x7F => .{ Mnemonic.RRA, AddressingMode.absoluteX },

        else => .{ Mnemonic.NOP, AddressingMode.implicit },
    };
}
